language: python
python:
   - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r tests/requirements-dev.txt
    - python setup.py install
before_script:
   - export PATH=$PATH:$PWD/bin
script:
   - PYTHONPATH=$PYTHONPATH:$PWD/pbs:$PWD nosetests tests --with-coverage --cover-erase --cover-package=pbs.custom
after_success:
    - coveralls
